### ISSUE TITLE
Hidden file access

### ISSUE THREAD

**Issue by ewerlinich** [briceio/ulauncher-baloo#1]
I am using Kubuntu and when using ULauncher I am unable to find hidden files. Is there any way to change this?

**Comment by briceio** [comment]
This plugin on balooctl, there is an option to index hidden files as well. Type this to see if you're actually indexing hidden files:

`balooctl config ls hidden`

You can then use the subcommand "set" to change the value of this setting. And then "balooctl check" to update the index.

I hope this help.
